vercel/edge-runtime

- packages/runtime/package.json
- packages/runtime/src/cli/repl.ts
- packages/runtime/src/edge-runtime.ts
- packages/runtime/tests/edge-runtime.test.ts
make `EdgeRuntime === 'edge-runtime'` & enable EdgeRuntime as global in the REPL
- https://github.com/vercel/next.js/pull/38288
> feat(runtime): make runtime addressable

- packages/primitives/scripts/build.ts
- packages/primitives/src/patches/undici-core-request.js
- packages/primitives/tests/fetch.test.ts
Fixes https://github.com/vercel/edge-functions/issues/172
The error `InvalidArgumentError: invalid connection header` comes from https://github.com/nodejs/undici/blob/v5.5.1/lib/core/request.js#L288 and unfortunately, it required to patch the entire file since it uses local function and a file-level local variable.
> fix(primitives): support all headers on fetch

- packages/runtime/src/cli/eval.ts
- packages/runtime/src/cli/index.ts
- packages/runtime/src/cli/logger.ts
- packages/runtime/src/cli/repl.ts
- packages/runtime/src/edge-runtime.ts
- packages/runtime/tests/repl.test.ts
- packages/vm/tests/unit/edge-vm.test.ts
This PR introduces `--eval` flag to run any inline script:
e.g.,:
```
$ edge-runtime --eval 'JSON.stringify(Object.getOwnPropertyNames(this))'
```
It's pretty similar to `node --eval`
closes #34
> feat(cli): add `--eval` flag

- packages/primitives/src/primitives/cache.js
- packages/primitives/src/primitives/crypto.js
- packages/primitives/tests/cache.test.ts
> refactor(primitives): remove fake native code

- packages/runtime/src/cli/help.ts
- packages/runtime/src/cli/index.ts
- Fixes https://github.com/vercel/edge-runtime/issues/6
- Doc: https://edge-runtime.vercel.app/cli
- This PR adds missing `help` flag for `edge-runtime` cli
```
$ edge-runtime --help
Usage: edge-runtime [input] [<flags>]
Flags:
--help   Display help message for flags.
--listen Interact with edge-runtime as an HTTP server.
--port   Specify a port to use.
--repl   Start an interactive session.
```
> fix(runtime): add help for CLI

- packages/types/src/index.d.ts
Adds definitions for the different timer functions ([Vercel documentation on support](https://vercel.com/docs/concepts/functions/edge-functions/edge-functions-api) says they are the same as v8 primitives)
> fix(primitives): add timer types definitions

- packages/primitives/types/url.d.ts
This reverts commit 3a5f0aa8b6e9e703f2f85dff3290879e99e50688.
#	packages/primitives/types/url.d.ts
> Revert "refactor(primitives): use types from urlpattern-polyfill"

- packages/primitives/tests/encoding.test.ts
- packages/primitives/tests/url.test.ts
- packages/vm/src/edge-vm.ts
- packages/vm/tests/unit/edge-vm.test.ts
Re: https://github.com/nextauthjs/next-auth/issues/5008
closes: https://github.com/vercel/edge-runtime/issues/63
/cc @Kikobeats
> fix: make `Uint8Array` available for `TextDecoder`

- packages/primitives/src/primitives/fetch.js
- packages/primitives/tests/fetch.test.ts
Unidici [is using process.nextTick()](https://cs.github.com/nodejs/undici?q=nextTick) in many places (along with `process.env` and `process.versions`), but we had no implementation for it.
This led to breaking POST requests. This PR should fix #61.
@Kikobeats added a unit test in this PR to check `POST` requests.
1. build the primitives: `pnpm --filter primitives build`
2. run their tests: `pnpm --filter primitives test`
You can also test it live in the VM:
1. build the whole project: `pnpm build`
2. open node: `node`
3. evaluate a fetch request: 
```js
const { EdgeVM } = require('./packages/vm')
new EdgeVM().evaluate(`fetch('https://httpbin.org/post', {method: 'POST', body: JSON.stringify({ foo: 'bar' }), headers: {'content-type': 'application/json'}}).then(r => r.json()).then(r => …
```
> fix(primitives): fetch POST not working due to missing internal

- docs/pages/packages/runtime.mdx
The url parsing logic in `initialCode` tries to extract a url from the `searchParams`. Also, there's an `await` missing.
> fix: docs example

- docs/pages/features/polyfills.mdx
Our links to polyfills got broken when we refactored them to fix `instanceof` operator.
On the [preview url](https://edge-runtime-git-docs-polyfills-links.vercel.sh/features/polyfills)
I'm not too sure about AggregateError. I couldn't found where we polyfill it (assuming we still do).
I'm also not very sure about how the information is presented on the page.
It's not very clear to me what happens:
1. is the runtime using http module when running on Node@12 only? what does it use when running on Node@14+?
2. is the runtime loading an http polyfill for Node@12 only? does it rely on node builtin when running on Node@14+?
I'd like we clarify this, but before I need your guidance in understanding it better.
> docs: fixes invalid links to polyfills

- package.json
- packages/user-agent/package.json
- packages/user-agent/src/index.ts
- packages/user-agent/test/index.test.ts
- packages/user-agent/tsup.config.ts
- pnpm-lock.yaml
This PR introduces `@edge-runtime/user-agent` package.
This is a very small library that is extracted from Next.js to allow all frameworks to integrate the user agent parsing logic. It's not a lot, but should be helpful nevertheless.
> feat: add @edge-runtime/user-agent for user agent parsing

- packages/vm/src/edge-vm.ts
Removes unrequired exposure of `ArrayBuffer` as a `global` for `encoding` module.
> refactor(vm): remove `ArrayBuffer` global

- jest.config.ts
- jest.setup.js
- packages/primitives/package.json
- packages/primitives/src/patches/undici-core-request.js
- packages/primitives/src/primitives/fetch.js
- packages/primitives/tests/abort-controller.test.ts
- packages/primitives/tests/encoding.test.ts
- packages/primitives/tests/request.test.ts
- packages/runtime/src/server/body-streams.ts
- packages/runtime/src/server/create-handler.ts
- packages/vm/src/edge-vm.ts
- pnpm-lock.yaml
When @Zxilly is playing around with Next.js API Route with Experimental Edge Runtime, he tries to get a body from an empty response (where its statusCode could be 204, 205, or 304, etc.). He gets an empty TypeError with it.
When I am tracking down the issue through Next.js' source code, I notice that the only way Next.js could throw an empty TypeError is through the pre-compiled version of Edge Runtime. Further digging leads me to the `nodejs/undici`. Then I find out that `undici` has already fixed the issue (https://github.com/nodejs/undici/pull/1508). With that PR merged, `undici` now throws fetch spec compliant error instead of an empty TypeError.
This change is landed in `undici@5.6.0`, `edge-runtime` is still using `undici@5.5.0`, thus the empty TypeError is still occurring in …
> chore(devDeps): bump undici to 5.10.0

- .changeset/eighty-badgers-beg.md
- packages/runtime/src/index.ts
- packages/runtime/src/server/body-streams.ts
- packages/runtime/src/server/create-handler.ts
- packages/runtime/src/server/index.ts
- packages/runtime/tests/server.test.ts
In Node.js `writable.write()` allows to pass not only `Uint8Array` but also `string`. Currently when a user creates a response with a stream that enqueues other types there is no validation when we read the chunks at put them in the Node.js server response which makes the write to fail and the server to hang.
With this PR we are adding a new helper that allows to create an async generator from the `response.body` `ReadableStream`. In this generator we will validate that the emitted chunk is a `Uint8Array` and if it is not we will throw an error. This will end up as an unhandled rejection failure since there is no way to handle the error as the response was already sent.
We also expose that util so that different server implementations can use it when piping the Edge Runtime response body …
> Add helper to validate body chunks

- .changeset/serious-papayas-dance.md
- packages/runtime/src/edge-runtime.ts
- packages/runtime/tests/edge-runtime.test.ts
- packages/runtime/tests/unhandled-rejection.test.ts
- packages/runtime/tests/unhandled-rejection.ts
Currently users can add an event listener using `addEventListener` for the `unhandledrejection` event. This handler is then invoked when an unhandled rejection occurs with an object that contains a `promise` and a `reason`. In Node.js the handler has a different signature and takes those two values into separated arguments. Currently we are invoking the handler using the Node.js signature while we should use `UnhandledPromiseRejection` instead. This PR fixes such issue and add some tests to ensure we are invoking the handler when there is an unhandled rejection.
> Fix `unhandledrejection` event shape

- .changeset/nasty-poets-ring.md
- packages/runtime/src/server/create-handler.ts
- packages/runtime/tests/unhandled-rejection.ts
When we are streaming and equeue a bad chunk we are correctly emitting an unhandled rejection but aside from this we must finish the response to make sure the client doesn't hang waiting for more chunks. With this PR we tweak the test for unhandled rejection so that it uses the server and we can also assert that the response is correctly finished.
> Update unhandled-rejection test to use a server

- .changeset/selfish-insects-suffer.md
- packages/runtime/src/edge-runtime.ts
- packages/runtime/tests/edge-runtime.test.ts
The Edge Runtime removes some unstable headers (see https://github.com/vercel/edge-runtime/pull/91) to be consistent to a regular fetch spec.
The thing is, under a redirect, headers can't be modified, so just I ward that lines to avoid users to threat with an unexpected error.
Plus, a redirect don't need to treat with headers since just 'location' is needed.
Closes #168
> fix: don't delete headers in a redirect

- package.json
Looks like contributors to this project are already using pnpm 7 due to the lockfile so lets formalize it with [Corepack](https://nodejs.org/api/corepack.html).
Try it out with by running `corepack enable`.
More info: https://styfle.dev/blog/corepack
> chore: bump pnpm@7.13.5

- .changeset/unlucky-icons-heal.md
- packages/cookies/src/index.ts
- packages/cookies/src/request-cookies.ts
- packages/cookies/src/response-cookies.ts
- packages/cookies/src/serialize.ts
- packages/cookies/test/response-cookies.test.ts
Changes based on the conversation in this [Slack thread](https://vercel.slack.com/archives/CGU8HUTUH/p1666109058231539).
Spec: https://wicg.github.io/cookie-store
Notable breaking changes:
- `ResponseCookies#get` has been renamed to `ResponseCookies#getValue` 
- `ResponseCookies#getWithOptions` has been renamed to `ResponseCookies#get`
> feat(cookies): make `RequestCookies` and `ResponseCookies` more spec compliant

- .changeset/breezy-geese-sneeze.md
- packages/cookies/src/index.ts
- packages/cookies/src/request-cookies.ts
- packages/cookies/src/response-cookies.ts
- packages/cookies/src/serialize.ts
- packages/cookies/src/types.ts
- packages/cookies/test/request-cookies.test.ts
- packages/cookies/test/response-cookies.test.ts
Using the same interface as [CookieStore](https://wicg.github.io/cookie-store/#dom-cookiestore-get) whenever possible.
Also, both `RequestCookies` and `ResponseCooies` will only receive `Headars` in the constructor, as they don't need more than that. (strictly speaking, we could just pass the cookie header value too...)
> feat(cookies): align `RequestCookies` and `ResponseCookies`

- .changeset/kind-falcons-jump.md
- docs/pages/packages/_meta.json
- docs/pages/packages/feature-detector.mdx
- packages/feature-detector/README.md
- packages/feature-detector/jest.config.ts
- packages/feature-detector/package.json
- packages/feature-detector/scripts/patch-type-definition.ts
- packages/feature-detector/src/has-edge-signature.ts
- packages/feature-detector/src/index.ts
- packages/feature-detector/src/utils/exports.ts
- packages/feature-detector/src/utils/functions.ts
- packages/feature-detector/src/utils/project.ts
- packages/feature-detector/src/utils/type-definition.txt
- packages/feature-detector/src/utils/types.ts
- packages/feature-detector/test/has-edge-signature.test.ts
- packages/feature-detector/test/test-utils.ts
- packages/feature-detector/test/utils/exports.test.ts
- packages/feature-detector/test/utils/functions.test.ts
- packages/feature-detector/test/utils/types.test.ts
- packages/feature-detector/tsconfig.prod.json
- packages/feature-detector/tsup.config.ts
- pnpm-lock.yaml
Here is the first stone of the feature detector package: detecting exported function with an edge signature.
This PR includes:
- the new `feature-detector` package
- the `hasEdgeSignature(filePath: string): boolean` function, fully tested. 
- documentation page (giant WIP with a useful example).
- README, redirecting to the documentation page.
The package is fully covered with unit tests: `pnpm --filter feature-detector test -- --coverage`
You can also try it out on a real file:
1. `pnpm --filter feature-detector build`
2. Create a file named `test.js` (or .ts)
3. start `node` REPL, and try it:
```shell
> const { hasEdgeSignature } = require('./packages/feature-detector/dist')
undefined
> hasEdgeSignature('./test.js')
false
4. change the file content and check its compliance with …
```
> feat(feature-detector): introduces edge signature detection

- packages/feature-detector/scripts/patch-type-definition.ts
When I try to build `feature-detector` package locally, it sometimes hangs my terminal.
I suspect that's happening because a lot of requests are performed in a little spare of time.
If I pass a keep-alive agent the build time is around 5 secs in a consistent way
> perf(feature-detector): speed up build time

- packages/feature-detector/package.json
- packages/types/src/index.d.ts
- turbo.json
This PR aims to fix using Edge Runtime types with a TypeScript project. 
Recently we noted they are not working as expected. 
That's easy to reproduce using the Vercel CLI. Simply create a `api/index.ts` with the following code inside:
```ts
export const config = {
runtime: 'experimental-edge'
};
export default async function handler(req: Request) {
await Promise.all<void>([]);
return new Response(`Hello from JS! ${new Date()}`);
}
```
Then run `vc dev` and hit the function. You should to see something like this:
Create `tsconfig.json` with the following content:
```json
{
"compilerOptions": {
"types": ["@edge-runtime/types"]
}
}
```
Then hit the server again. Now the error is types conflicts:
If you open `node_modules/@edge-runtime/types/src/index.d.ts` you can see the conflicts:
If you …
> fix(types): avoid to re-export already declared

- packages/primitives/scripts/build.ts
Hello,
TS is crying because the right types for https://github.com/igoradamenko/esbuild-plugin-alias in our current esbuild version is missing:
However, the library can still be used as usual. I verified that checking `dist/fetch` is using our `util/types` patch for node12:
> fix: ignore missing type for alias

- .changeset/curvy-bikes-greet.md
- .changeset/dry-cheetahs-fail.md
- docs/pages/packages/node-utils.mdx
- package.json
- packages/node-utils/src/edge-to-node/handler.ts
- packages/node-utils/src/node-to-edge/fetch-event.ts
- packages/node-utils/src/node-to-edge/index.ts
- packages/node-utils/src/node-to-edge/request.ts
- packages/node-utils/src/types.ts
- packages/node-utils/test/edge-to-node/handler.test.ts
- packages/node-utils/test/node-to-edge/fetch-event.test.ts
- packages/node-utils/test/node-to-edge/request.test.ts
- packages/node-utils/test/test-utils/run-test-server.ts
- pnpm-lock.yaml
- turbo.json
Current node-utils have a fixed origin for mapped web requests. A better solution is to leverage the incomingMessage's `host` header, and only default to a fixed value in case the header is missing.
This PR also brings a mocked `fetchEvent` (web handler second parameter). It will throw when using `waitUntil()`,  so our users would know this feature is not implemented yet.
- feat(node-utils): uses incoming host header to determine request's origin
- feat(node-utils): provides mocked fetch event which throws on waitUntil
- fix(ci): reverts jest version bump from dependabot which broke [main](https://github.com/vercel/edge-runtime/commit/64ae0773760aa1eab6ceaa15090f56f616ca9dec)
It is likely that no one is using this package. Yet, these are 2 breaking changes, since the required options and …
> feat(node-utils): uses host header and mocks waitUntil()

- .changeset/funny-sheep-join.md
- packages/runtime/package.json
- packages/runtime/src/server/create-handler.ts
- pnpm-lock.yaml
I noted this dependency isn't necessary since it's available in Node.js 😆
> refactor: remove unnecessary dependency

- .changeset/heavy-rabbits-glow.md
- packages/cookies/src/response-cookies.ts
- packages/cookies/src/serialize.ts
- packages/cookies/test/response-cookies.test.ts
- pnpm-lock.yaml
Currently, if a user sets multiple cookies in a series, only the second cookie is set in the `set-cookie` header.
When this is merged, I will update https://github.com/vercel/next.js/tree/canary/packages/next/src/server/web/spec-extension/cookies to drop the code and use the pre-compiled version of this package again.
[Slack thread 1](https://vercel.slack.com/archives/C03S8ED1DKM/p1675694485304329), [Slack thread 2](https://vercel.slack.com/archives/C03ENM5HB4K/p1668173326539069)
> fix(cookies): be able to split `set-cookie` without `getAll`

- .changeset/twenty-dancers-swim.md
- packages/node-utils/src/edge-to-node/headers.ts
- packages/primitives/type-definitions/fetch.d.ts
Follow-up on: #255
Blocking to upgrade `edge-runtime` packages in https://github.com/vercel/next.js/pull/42736
> fix(ts): mark `.getAll()` as optional

- .github/workflows/test.yml
CI will always fail because `@edge-runtime/docs` is not compatible with Node.js v14. CI will exclude the `@edge-runtime/docs` build so that it will pass CI. The `@edge-runtime/docs` build should be secured by deploying to Vercel.
> ci: skip docs build

- .changeset/unlucky-items-swim.md
- package.json
- packages/cookies/package.json
- packages/feature-detector/package.json
- packages/format/package.json
- packages/jest-environment/package.json
- packages/jest-expect/package.json
- packages/node-utils/package.json
- packages/ponyfill/package.json
- packages/primitives/package.json
- packages/runtime/package.json
- packages/types/package.json
- packages/user-agent/package.json
- packages/vm/package.json
This will help users with automated license checking tools.
[List of valid SPDX license expressions](https://spdx.org/licenses/)
Closes https://github.com/vercel/edge-runtime/issues/274
> fix: use valid SPDX license expression

- .changeset/honest-worms-add.md
- packages/cookies/src/response-cookies.ts
- packages/cookies/src/serialize.ts
- packages/cookies/src/types.ts
- packages/cookies/test/response-cookies.test.ts
According to the [W3C CookieStore API spec](https://wicg.github.io/cookie-store/#dictdef-cookielistitem), expires accepts [`DOMHighResTimeStamp`](https://w3c.github.io/hr-time/#dom-domhighrestimestamp) but `@edge-runtime/cookies` only accepts `Date` interface. Change to accept both `DOMHighResTimeStamp` and `Date` interface for backwards compatibility instead of replacing `Date` interface.
> fix(cookies): accept `DOMHighResTimeStamp` on expires of cookie

- docs/pages/getting-started.mdx
- docs/pages/packages/runtime.mdx
- packages/runtime/examples/cache.js
- packages/runtime/examples/fetch.js
- packages/runtime/package.json
- packages/runtime/src/cli/index.ts
- pnpm-lock.yaml
- use `signal-exit` instead of `exit-hook` (it's tinier).
- fix getting started example showcasing how to interact with Edge Runtime via local server. 
- prefer `example.vercel.sh` over `example.com`
closes #319
> docs(getting-started): improve example

- .changeset/beige-lions-film.md
- packages/jest-environment/src/index.ts
This should make it so that if you import the 'server-only' poison pill module, it does not throw an error, because the module resolver will interpret it as a server module instead of a client one.
> Add "react-server" export condition to Jest environment

- .changeset/cold-geckos-serve.md
- packages/primitives/src/primitives/index.js
- packages/vm/tests/integration/crypto.test.ts
This change makes it so that if the node process has a webcrypto API implementation that this implementation be used instead of `@peculiar/webcrypto` so that Ed25519 and X25519 algorithms become available.
~It also patches out the use of Ed448 and X448 Algorithms which are not present in Edge Functions at Vercel. Ed25519 and X25519 already is (or should be?) since it's already present in workerd and CF Workers. This prototype update can easily be omitted but then EdgeRuntime would support more than the Edge Functions at Vercel runtime... This way they're aligned, but it's ugly and messes with the prototype when using edge runtime programatically... I'm happy to remove it from the PR~
The @peculiar/webcrypto dependency can be safely dropped when node 14 support is removed.
> use node's webcrypto when available

- .changeset/tender-berries-hunt.md
- packages/integration-tests/tests/headers.test.ts
- packages/primitives/src/primitives/fetch.js
it yielded the same set-cookie header twice
> fix entires iteration for cookies

- .changeset/serious-moons-remain.md
- packages/primitives/scripts/build.ts
- packages/primitives/src/injectSourceCode.d.ts
- packages/primitives/src/primitives/load.js
this PR removes the required (explicit) file system read in favor of static `require` calls,
which is practically an implicit file system read, but statically analyzable by bundlers.
> remove dynamism in imports

- .changeset/violet-birds-study.md
- packages/primitives/.gitignore
- packages/primitives/package.json
- packages/primitives/scripts/build.ts
in one of the latest PRs we introduced `file.js.text.js` which contains the entire generated module, serialized as a string, to avoid `fs` usage.
this PR removes the original `file.js` files as they are not needed. This is a breaking change because now people won't be able to import specific packages like `@edge-runtime/primitives/crypto` but I don't think this is an issue as this would break anyway as there's a certain order to these imports. The better way is to import the ponyfill.
> remove javascript files in favor of only having the text imports

- .changeset/red-chefs-lick.md
- packages/primitives/package.json
- packages/primitives/src/primitives/encoding.js
- packages/primitives/src/primitives/load.js
- packages/primitives/src/primitives/url.js
- pnpm-lock.yaml
I believe `whatwg-url` was added to be possible evaluate correctly `instanceof URL` inside vm and it's no more necessary 🙂
closes https://github.com/vercel/edge-runtime/issues/261
> chore(primitives): remove unnecessary polyfills

- .changeset/thirty-goats-complain.md
- packages/runtime/src/cli/repl.ts
So next time you open a REPL session, your previous commands are there:
> chore(repl): add history

- .changeset/swift-berries-argue.md
- packages/cookies/src/serialize.ts
- packages/cookies/test/response-cookies.test.ts
Perviously, cookies with attributes were not parsed correctly, namely:
```
Set-Cookie: my_value=true; Secure; HttpOnly
```
Did not correctly parse out the `Secure` and `HttpOnly` attributes. This addresses this by handling the edge case where there is no trailing `=` character after the attribute name (like for `HttpOnly` and `Secure`).
> Fixed Cookie Parsing

- .changeset/silent-plums-march.md
- packages/runtime/package.json
- packages/runtime/src/server/body-streams.ts
- packages/runtime/tests/body-stream.test.ts
- pnpm-lock.yaml
Right now, `consumeUint8ArrayReadableStream` never explicitly closes the the readable stream we're consuming from. Unfortunately that means that devs aren't able to release their resources, leaking them until the GC eventually runs.
This is important for the AI streaming use case, so that devs can detect that a client has disconnected the stream and in turn disconnect the fetch they're maintaining to the AI service.
> Ensure we cancel `consumeUint8ArrayReadableStream` if iteration breaks

- .changeset/calm-paws-sip.md
- docs/pages/packages/cookies.mdx
- packages/cookies/src/index.ts
- packages/cookies/src/request-cookies.ts
- packages/cookies/src/response-cookies.ts
- packages/cookies/src/serialize.ts
- packages/cookies/test/request-cookies.test.ts
- packages/cookies/test/serialize.test.ts
- packages/node-utils/package.json
- packages/node-utils/src/edge-to-node/headers.ts
- packages/primitives/package.json
- packages/types/package.json
- packages/user-agent/package.json
- pnpm-lock.yaml
Also, provided a more helpful `ResponseCookies` example that clarifies response headers should be written by the user code:
```js
function handleRequest(req: Request) {
const headers = new Headers()
const cookies = new ResponseCookies()
cookies.set('cookie-name', 'cookie-value', { maxAge: 1000 }) // make cookie persistent for 1000 seconds
cookies.delete('old-cookie')
return new Response('', {
headers: {
'set-cookie': headers.getAll?.('set-cookie'),
},
}
```
> chore(cookies): exposes `.splitCookiesString`

- .changeset/mighty-nails-invite.md
- packages/cookies/src/response-cookies.ts
- packages/cookies/test/request-cookies.test.ts
- packages/cookies/test/response-cookies.test.ts
> Since Next.js cookies function returns ResponseCookies as ReadonlyRequestCookies in server requests, cookies().has(//...) throws a TypeError .has is not a function.
Added `has` in ResponseCookies and tests.
Fixes: #532 [Next.js-#54005](https://github.com/vercel/next.js/discussions/54005)
> fix(cookies): add `.has` in `ResponseCookies`

- package.json
- packages/cookies/package.json
- packages/format/package.json
- packages/integration-tests/tests/abort-controller.test.ts
- packages/jest-environment/package.json
- packages/jest-expect/package.json
- packages/node-utils/package.json
- packages/ponyfill/package.json
- packages/primitives/package.json
- packages/primitives/scripts/build.ts
- packages/primitives/src/primitives/crypto.js
- packages/primitives/src/primitives/events.js
- packages/primitives/src/primitives/fetch.js
- packages/primitives/src/primitives/load.js
- packages/primitives/src/primitives/streams.js
- packages/primitives/src/primitives/text-encoding-streams.js
- packages/primitives/type-definitions/events.d.ts
- packages/runtime/package.json
- packages/types/package.json
- packages/user-agent/package.json
- packages/vm/package.json
- packages/vm/tests/edge-runtime.test.ts
- packages/vm/tests/instanceof.test.ts
- pnpm-lock.yaml
It drops the following polyfills:
Closes #537
> feat(primitives): drop node14

- .changeset/slimy-seals-confess.md
- packages/integration-tests/tests/response.test.ts
- packages/primitives/src/primitives/fetch.js
- packages/primitives/type-definitions/fetch.d.ts
To introduce fewer breaking changes, this adds back the non-spec compliant `Headers#getAll` method (that was removed in #586) but still encourages the use of `Headers#getSetCookie` instead which is [part of the standard](https://fetch.spec.whatwg.org/#dom-headers-getsetcookie).
**Context:** `getAll` exists because `getSetCookie` did not exist at the time of `edge-runtime` being created.
[_We were young and needed to ship_](https://twitter.com/cramforce/status/949054860166553600).
Ref: [Slack thread](https://vercel.slack.com/archives/C03ENM5HB4K/p1694088078677229)
> feat: revert `.getAll` removal, mark deprecated

- .changeset/fifty-eagles-invite.md
- packages/cookies/src/serialize.ts
- packages/cookies/test/response-cookies.test.ts
Closes https://github.com/vercel/next.js/issues/56848
This PR provides the fix for cookies() .set() to reflect the priority attribute into set-cookie
RE: @balazsorban44's comment and request change on https://github.com/vercel/next.js/pull/56850 Pull Request: 
"Thanks for the PR, the @edge-runtime/cookies package is an upstream dependency, meaning it should be addressed there first, could you open these changes there, so we can bump the package here to incorporate it?
See https://github.com/vercel/edge-runtime/blob/main/packages/cookies/src/serialize.ts#L16"
> fix: cookies() .set() reflect priority attribute into set-cookie

- .changeset/olive-maps-remember.md
- packages/integration-tests/tests/encoding.test.ts
- packages/primitives/src/primitives/encoding.js
- packages/primitives/type-definitions/encoding.d.ts
`btoa` can accept any value that will be cast as a string.
Closes https://github.com/vercel/edge-runtime/issues/638
> fix(btoa): it accepts any as argument

- .changeset/violet-carrots-listen.md
- packages/primitives/package.json
- packages/primitives/src/primitives/encoding.js
- packages/primitives/src/primitives/load.js
- packages/primitives/type-definitions/encoding.d.ts
- turbo.json
It isn't necessary, the native Node.js implementation can be used.
> feat(primitives): remove atob/btoa implementation

- packages/node-utils/src/node-to-edge/request.ts
- packages/node-utils/test/node-to-edge/request.test.ts
This PR fixes the problem of missing origin with double slash paths.
```js
new URL("//foo.com", "https://example.com");
// => 'https://foo.com/'
```
> fix(buildToRequest): double slash path

- .changeset/perfect-fans-heal.md
- package.json
- packages/jest-environment/package.json
- pnpm-lock.yaml
Currently we are unable to publish any Next.js versions that include the `jest-environment` package in the true due to a bug in the `npmcli` that attempts resolving the dependency tree during a publish but fails to handle a circular dependency. 
Hoisting the `next` `devDependency` to the root should resolve this issue. 
x-ref: [slack thread](https://vercel.slack.com/archives/C04KC8A53T7/p1707072786476149)
> Fix dependency conflict with Next.js package

- .changeset/new-jars-live.md
- packages/cookies/src/serialize.ts
- packages/cookies/src/types.ts
- packages/cookies/test/response-cookies.test.ts
Chrome already started rolling/enforcing this feature (currently at 1%).
> feat(cookies): support `partitioned` attribute

- .changeset/fast-hairs-pull.md
- packages/cookies/src/serialize.ts
- packages/cookies/test/request-cookies.test.ts
- [Spec](https://datatracker.ietf.org/doc/html/rfc6265#section-4.2.1:~:text=cookie%2Dheader%20%3D%20%22Cookie%3A%22%20OWS%20cookie%2Dstring%20OWS%0A%20%20%20cookie%2Dstring%20%3D%20cookie%2Dpair%20*(%20%22%3B%22%20SP%20cookie%2Dpair%20))
- It seems incorrect to have a trailing semicolon.
> fix(cookies): cookie header format

- .changeset/afraid-seahorses-argue.md
- packages/runtime/src/server/run-server.ts
Waiting `waitUntil` and closing the server can be done in parallel.
> perf: speed up server close

- .changeset/dirty-timers-reply.md
- packages/integration-tests/package.json
- packages/integration-tests/test/abort-controller.test.ts
- packages/integration-tests/test/body.test.ts
- packages/integration-tests/test/crypto.test.ts
- packages/integration-tests/test/env.d.ts
- packages/integration-tests/test/fetch.test.ts
- packages/integration-tests/test/headers.test.ts
- packages/integration-tests/test/request.test.ts
- packages/integration-tests/test/response.test.ts
- packages/integration-tests/test/test-if.ts
- packages/primitives/src/primitives/fetch.js
- pnpm-lock.yaml
`Headers.prototype.entries` was different from `Headers.prototype[Symbol.iteartor]`. This is probably a fairly new implementation in undici that handles set-cookie headers, so I removed the custom `entries()` function.
This resolves EC-2421
> [primitives] fix Headers#entries implementation to be consistent

- .changeset/tasty-cats-eat.md
- packages/format/src/index.ts
- packages/format/tests/index.test.ts
- packages/vm/tests/integration/error.test.ts
- **[format] breaking: print stack trace when logging errors**
- **add changeset**
Closes https://github.com/vercel/edge-runtime/issues/108
> [format] print stack trace by default

- .changeset/big-pumpkins-kiss.md
- packages/cookies/src/serialize.ts
- packages/cookies/test/response-cookies.test.ts
> fix: parse max-age in set cookie

- .changeset/sweet-trees-press.md
#1025 was merged but we haven't declared a changeset for `@edge-runtime/primitives` so it wasn't released (seems like Changesets doesn't do what we want it to do)
This PR forces to bump primitives:
```
🦋  info Packages to be bumped at patch:
🦋  info
🦋  - @edge-runtime/primitives
🦋  - @edge-runtime/types
🦋  - @edge-runtime/vm
🦋  - @edge-runtime/jest-environment
🦋  - edge-runtime
🦋  ---
🦋  info NO packages to be bumped at minor
🦋  ---
🦋  info NO packages to be bumped at major
```
> force bump primitives
