vercel/edge-runtime

- packages/primitives/types/streams.d.ts
- packages/vm/src/edge-vm.ts
This PR removes some not required dependency injection for the `vm` and adds a hardcoded type so we don't have to include as a dependency `web-streams-polyfill`.
> Minor fixes

- docs/pages/cli.mdx
> Fix CLI local web server docs

- docs/pages/features/available-apis.mdx
Slack thread: https://vercel.slack.com/archives/C03ENM5HB4K/p1659360397158669?thread_ts=1659358456.405629&cid=C03ENM5HB4K
> docs: add note on how to address the runtime

- packages/vm/src/edge-vm.ts
- packages/vm/tests/integration/crypto.test.ts
- pnpm-lock.yaml
- chore: update pnpm-lock.yaml
- fix(vm): make sure instanceof checks for ArrayBuffer work when using crypto
> fix(vm): make sure instanceof checks for ArrayBuffer work when using crypto

- packages/jest-environment/src/index.ts
- packages/jest-environment/test/index.test.ts
- packages/runtime/src/edge-runtime.ts
- packages/vm/src/edge-vm.ts
- turbo.json
> fix(jest-enviroment): add EdgeRuntime global

- packages/user-agent/tsconfig.json
- pnpm-lock.yaml
- turbo.json
- fix: @edge-runtime/primitives Turborepo output
- fix: add tsconfig.json to @edge-runtime/user-agent
- chore: update pnpm-lock.yaml
> fix: tsc/turborepo build issues

- docs/next.config.js
- docs/package.json
- docs/pages/packages/format.mdx
- docs/pages/packages/jest-environment.mdx
- docs/pages/packages/meta.json
- docs/pages/packages/ponyfill.mdx
- docs/pages/packages/primitives.mdx
- docs/pages/packages/runtime.mdx
- docs/pages/packages/types.mdx
- docs/pages/packages/vm.mdx
- pnpm-lock.yaml
> docs: add format section

- .changeset/tall-lies-invite.md
- .changeset/thick-pets-brush.md
- packages/ponyfill/package.json
- packages/ponyfill/src/index.js
- packages/ponyfill/test/acorn.d.ts
- packages/ponyfill/test/compliance-with-primitives.node.test.ts
- packages/primitives/type-definitions/cache.d.ts
- pnpm-lock.yaml
This makes it more concise and easier to use.
> Make ponyfill only export the explicitly typed values

- docs/pages/packages/format.mdx
> docs: fix typos

- packages/format/src/index.ts
- packages/format/src/primordials.ts
- packages/format/tests/index.test.ts
> fix(format): should format success on null prototyped object

- .changeset/three-kangaroos-study.md
- docs/pages/packages/cookies.mdx
> docs(cookies): update docs to reflect implementation

- .github/workflows/publish.yml
- .github/workflows/test.yml
- .github/workflows/update.yml
This is a follow up to https://github.com/vercel/edge-runtime/pull/176
> chore: use corepack for CI

- docs/pages/index.mdx
Adjusts the wording around our association with WinterCG
> Adjust WinterCG Wording

- .changeset/seven-adults-decide.md
- packages/primitives/type-definitions/events.d.ts
- packages/types/src/index.d.ts
> fix: add missing types

- .changeset/khaki-experts-refuse.md
- packages/format/src/index.ts
- packages/format/tests/index.test.ts
> feat: provide formatter inside custom symbol

- .github/workflows/test.yml
We've decided to phase it out!
> chore: Remove codecov

- .github/workflows/publish.yml
- .github/workflows/test.yml
- package.json
- packages/cookies/README.md
- packages/cookies/package.json
- packages/feature-detector/README.md
- packages/feature-detector/package.json
- packages/format/package.json
- packages/jest-environment/package.json
- packages/jest-expect/package.json
- packages/node-utils/README.md
- packages/node-utils/package.json
- packages/ponyfill/package.json
- packages/primitives/package.json
- packages/primitives/scripts/build.ts
- packages/runtime/package.json
- packages/types/package.json
- packages/user-agent/README.md
- packages/user-agent/package.json
- packages/vm/package.json
- pnpm-lock.yaml
Some tweaks, but essentially:
- Locked dependencies.
- Added missing README on packages.
- Added keywords on package.json.
- Ensure `files` is defined at package.json.
> docs: tweaks

- .changeset/wild-pillows-fold.md
- packages/cookies/src/serialize.ts
- packages/cookies/test/request-cookies.test.ts
Incorporates https://github.com/vercel/next.js/pull/44218
> fix(cookies): only split on first occurrence of "="

- .changeset/clean-kings-learn.md
- packages/integration-tests/tests/request.test.ts
- packages/primitives/src/primitives/fetch.js
- make Request extend BaseRequest
- use Proxy, but use the receiver class, and add a test
- add changeset
> bugfix: allow Request to be extended

- .changeset/famous-phones-cheer.md
- packages/primitives/src/primitives/load.js
- [primitives] use path.join instead of path.resolve
- changeset
> use path join instead of path resolve

- .changeset/slow-moose-promise.md
- packages/primitives/package.json
- pnpm-lock.yaml
- bump undici to v5.22.1
- bump undici version
> bump undici

- .changeset/afraid-garlics-fail.md
- packages/integration-tests/tests/blob.test.ts
- packages/primitives/scripts/build.ts
- packages/primitives/src/primitives/load.js
Don't override Blob and use it if a global version available.
> [primitives] don't override Blob global

- packages/user-agent/src/index.ts
context: https://github.com/vercel/next.js/pull/50467
> Add new `Google-InspectionTool` token to known bot UA list

- .changeset/fast-crews-report.md
- packages/types/src/index.d.ts
closes https://github.com/vercel/edge-runtime/issues/469
> fix: remove createCaches type

- packages/cookies/src/index.ts
- packages/cookies/test/index.test.ts
> feat(cookies): expose serialization functions

- packages/integration-tests/tests/encoding.test.ts
closes https://github.com/vercel/edge-runtime/issues/638
> test: add atob and btoa cases

- .changeset/hungry-bananas-lay.md
- packages/primitives/package.json
- packages/primitives/scripts/build.ts
- pnpm-lock.yaml
- **[primitives] minify sources**
- **add changeset**
> [primitives] minify sources

- packages/cookies/README.md
- packages/format/README.md
A small drive-by PR with a couple fix-ups for incorrect doc URLs.
Have a nice day! ☀️
> docs: fix some incorrect README docs URLs
